[project]
name = "agent-s"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.72.0",
    "backoff>=2.2.1",
    "black>=25.9.0",
    "fastapi>=0.120.1",
    "google-genai>=1.46.0",
    "numpy>=2.3.4",
    "openai>=2.6.1",
    "paddleocr>=3.3.0",
    "paddlepaddle>=3.2.0",
    "pandas>=2.3.3",
    "pyautogui>=0.9.54",
    "pytesseract>=0.3.13",
    "scikit-learn>=1.7.2",
    "tiktoken>=0.12.0",
    "together>=1.5.29",
    "toml>=0.10.2",
    "uvicorn>=0.38.0",
    "websockets>=15.0.1",
    "pyobjc; sys_platform == 'darwin'",
    "pywinauto; sys_platform == 'win32'",
    "pywin32; sys_platform == 'win32'",
    "dotenv-python>=0.0.1",
    "python-dotenv>=1.2.1",
    "mlflow>=3.5.1",
    "dspy>=3.0.4",
]
